# File: pnpm-workspace.yaml

packages:
  - 'apps/*'
  - 'packages/*'
  - 'api'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@soulwax/d-fi'
  - '@swc/core'
  - bcrypt
  - canvas
  - electron
  - electron-winstaller
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
