-- File: apps/web/drizzle/0022_startpage_taste_profile.sql

CREATE TABLE IF NOT EXISTS "hexmusic-stream_user_taste_profile" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "userId" varchar(255) NOT NULL UNIQUE,
  "preferredGenreId" integer,
  "preferredGenreName" varchar(120),
  "seedArtists" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "seedPlaylistTitles" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
  "updatedAt" timestamp with time zone
);

DO $$ BEGIN
 ALTER TABLE "hexmusic-stream_user_taste_profile"
 ADD CONSTRAINT "hexmusic-stream_user_taste_profile_userId_hexmusic-stream_user_id_fk"
 FOREIGN KEY ("userId") REFERENCES "public"."hexmusic-stream_user"("id")
 ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

CREATE INDEX IF NOT EXISTS "user_taste_profile_user_idx"
  ON "hexmusic-stream_user_taste_profile" ("userId");
CREATE INDEX IF NOT EXISTS "user_taste_profile_genre_idx"
  ON "hexmusic-stream_user_taste_profile" ("preferredGenreId");
