-- File: apps/web/drizzle/0023_handy_karnak.sql

CREATE TABLE "hexmusic-stream_user_taste_profile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hexmusic-stream_user_taste_profile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(255) NOT NULL,
	"preferredGenreId" integer,
	"preferredGenreName" varchar(120),
	"seedArtists" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"seedPlaylistTitles" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "hexmusic-stream_user_taste_profile_userId_unique" UNIQUE("userId")
);
--> statement-breakpoint
ALTER TABLE "hexmusic-stream_user_taste_profile" ADD CONSTRAINT "hexmusic-stream_user_taste_profile_userId_hexmusic-stream_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "user_taste_profile_user_idx" ON "hexmusic-stream_user_taste_profile" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "user_taste_profile_genre_idx" ON "hexmusic-stream_user_taste_profile" USING btree ("preferredGenreId");--> statement-breakpoint
CREATE UNIQUE INDEX "unique_first_admin" ON "hexmusic-stream_user" USING btree ("firstAdmin") WHERE "hexmusic-stream_user"."firstAdmin" = true;
