CREATE TABLE "hexmusic-stream_friend_request" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hexmusic-stream_friend_request_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"requesterUserId" varchar(255) NOT NULL,
	"recipientUserId" varchar(255) NOT NULL,
	"status" varchar(20) DEFAULT 'pending' NOT NULL,
	"message" varchar(500),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"respondedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "hexmusic-stream_friendship" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hexmusic-stream_friendship_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userAId" varchar(255) NOT NULL,
	"userBId" varchar(255) NOT NULL,
	"createdByUserId" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "friendship_pair_unique" UNIQUE("userAId","userBId")
);
--> statement-breakpoint
CREATE TABLE "hexmusic-stream_playlist_collaborator" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hexmusic-stream_playlist_collaborator_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"playlistId" integer NOT NULL,
	"userId" varchar(255) NOT NULL,
	"role" varchar(20) DEFAULT 'editor' NOT NULL,
	"status" varchar(20) DEFAULT 'invited' NOT NULL,
	"invitedByUserId" varchar(255),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"acceptedAt" timestamp with time zone,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "playlist_collaborator_playlist_user_unique" UNIQUE("playlistId","userId")
);
--> statement-breakpoint
CREATE TABLE "hexmusic-stream_user_block" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hexmusic-stream_user_block_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"blockerUserId" varchar(255) NOT NULL,
	"blockedUserId" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "user_block_pair_unique" UNIQUE("blockerUserId","blockedUserId")
);
--> statement-breakpoint
ALTER TABLE "hexmusic-stream_playlist_track" ADD COLUMN "addedByUserId" varchar(255);--> statement-breakpoint
ALTER TABLE "hexmusic-stream_playlist_track" ADD COLUMN "updatedByUserId" varchar(255);--> statement-breakpoint
ALTER TABLE "hexmusic-stream_playlist" ADD COLUMN "isCollaborative" boolean DEFAULT false NOT NULL;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_playlist" ADD COLUMN "collaborationMode" varchar(40) DEFAULT 'owner_invite_only' NOT NULL;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_playlist" ADD COLUMN "collaborationUpdatedAt" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_friend_request" ADD CONSTRAINT "hexmusic-stream_friend_request_requesterUserId_hexmusic-stream_user_id_fk" FOREIGN KEY ("requesterUserId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_friend_request" ADD CONSTRAINT "hexmusic-stream_friend_request_recipientUserId_hexmusic-stream_user_id_fk" FOREIGN KEY ("recipientUserId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_friendship" ADD CONSTRAINT "hexmusic-stream_friendship_userAId_hexmusic-stream_user_id_fk" FOREIGN KEY ("userAId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_friendship" ADD CONSTRAINT "hexmusic-stream_friendship_userBId_hexmusic-stream_user_id_fk" FOREIGN KEY ("userBId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_friendship" ADD CONSTRAINT "hexmusic-stream_friendship_createdByUserId_hexmusic-stream_user_id_fk" FOREIGN KEY ("createdByUserId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_playlist_collaborator" ADD CONSTRAINT "hexmusic-stream_playlist_collaborator_playlistId_hexmusic-stream_playlist_id_fk" FOREIGN KEY ("playlistId") REFERENCES "public"."hexmusic-stream_playlist"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_playlist_collaborator" ADD CONSTRAINT "hexmusic-stream_playlist_collaborator_userId_hexmusic-stream_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_playlist_collaborator" ADD CONSTRAINT "hexmusic-stream_playlist_collaborator_invitedByUserId_hexmusic-stream_user_id_fk" FOREIGN KEY ("invitedByUserId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_user_block" ADD CONSTRAINT "hexmusic-stream_user_block_blockerUserId_hexmusic-stream_user_id_fk" FOREIGN KEY ("blockerUserId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_user_block" ADD CONSTRAINT "hexmusic-stream_user_block_blockedUserId_hexmusic-stream_user_id_fk" FOREIGN KEY ("blockedUserId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "friend_request_requester_idx" ON "hexmusic-stream_friend_request" USING btree ("requesterUserId");--> statement-breakpoint
CREATE INDEX "friend_request_recipient_idx" ON "hexmusic-stream_friend_request" USING btree ("recipientUserId");--> statement-breakpoint
CREATE INDEX "friend_request_status_idx" ON "hexmusic-stream_friend_request" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "friend_request_pending_pair_idx" ON "hexmusic-stream_friend_request" USING btree ("requesterUserId","recipientUserId") WHERE "hexmusic-stream_friend_request"."status" = 'pending';--> statement-breakpoint
CREATE INDEX "friendship_user_a_idx" ON "hexmusic-stream_friendship" USING btree ("userAId");--> statement-breakpoint
CREATE INDEX "friendship_user_b_idx" ON "hexmusic-stream_friendship" USING btree ("userBId");--> statement-breakpoint
CREATE INDEX "playlist_collaborator_playlist_idx" ON "hexmusic-stream_playlist_collaborator" USING btree ("playlistId");--> statement-breakpoint
CREATE INDEX "playlist_collaborator_user_idx" ON "hexmusic-stream_playlist_collaborator" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "playlist_collaborator_status_idx" ON "hexmusic-stream_playlist_collaborator" USING btree ("status");--> statement-breakpoint
CREATE INDEX "user_block_blocker_idx" ON "hexmusic-stream_user_block" USING btree ("blockerUserId");--> statement-breakpoint
CREATE INDEX "user_block_blocked_idx" ON "hexmusic-stream_user_block" USING btree ("blockedUserId");--> statement-breakpoint
ALTER TABLE "hexmusic-stream_playlist_track" ADD CONSTRAINT "hexmusic-stream_playlist_track_addedByUserId_hexmusic-stream_user_id_fk" FOREIGN KEY ("addedByUserId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hexmusic-stream_playlist_track" ADD CONSTRAINT "hexmusic-stream_playlist_track_updatedByUserId_hexmusic-stream_user_id_fk" FOREIGN KEY ("updatedByUserId") REFERENCES "public"."hexmusic-stream_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "playlist_track_added_by_idx" ON "hexmusic-stream_playlist_track" USING btree ("addedByUserId");